name: Test

on: [push, pull_request, workflow_dispatch]

permissions:
  contents: read
  
jobs:
  build:

    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-18.04"]
        python-version: ["3.6", "3.7"]
        include:
        # Include new variables for Codecov
        - os: ubuntu-18.04
          codecov-flag: GHA_Ubuntu

    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }} Python ${{ matrix.python-version }}

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Build system information
      run: python3 .github/workflows/system-info.py        

    - name: Install opencv dependencies
      run: |
        sudo rm /etc/apt/sources.list.d/*
        sudo apt-get update
        sudo apt-get install -y libgl1 libsm6 libxext6

    - name: Install python dependencies
      run: |
        pip install pytest pytest-mock
        pip install .
 
    - name: Test with pytest
      run: |
        pytest Test
        
    - name: Upload coverage
      run: bash <(curl -s https://codecov.io/bash) -F ${{ matrix.codecov-flag }}
      env:
        CODECOV_NAME: ${{ matrix.os }} Python ${{ matrix.python-version }}
        
        
  success:
    permissions:
      contents: none
    needs: build
    runs-on: ubuntu-latest
    name: Test Successful
    steps:
      - name: Success
        run: echo Test Successful
